### ISSUE TITLE
Improve VM template version handling

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/ez-rancher#101]
Using PR #100 (I assume existing branches work the same way):

- Deploy Bionic OVA linked from README.md
- Run `ez-rancher` using the above mentioned PR

Problem: outdated VM HW Version (originating from the Bionic OVA)

![image](https://user-images.githubusercontent.com/16622642/100723746-20810180-33fd-11eb-80e1-03b3e2fa4a54.png)

[Here](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-789C3913-1053-4850-A0F0-E29C3D32B6DA.html) we can find several potential reasons why we should use a more recent VM hardware version: 
 
- Maximum 3D graphics memory (GB)
- Virtual Precision Clock device
- Virtual Watchdog Timer device
- Virtual I/O MMU

There are other differences, less relevant to NetApp HCI.

GPU workloads, NOSQL and several other workloads that are increasingly deployed on Kubernetes may require one or more of these features. Not necessarily on Management Cluster, but users can also clone Management Cluster nodes to deploy User Clusters and Precision Clock and Watchdog Timer may be useful for Management Clusters (I haven't looked into this yet). 

I also have some opinions.

### In VM Template

- Only update README.md to remind users to change HW version in the template VM to one appropriate for their vSphere environment
- Pro's: One-off change, can't go wrong with it, nothing to change in the code
- Con's: Nobody RTFM

### In `ez-rancher`

- Because NetApp HCI NDE currently deploys v6.7, I'd like to see HW version 14 supported by default and a small note about that in README.md. Later on, possibly add a parameter to `rancher.tfvars`. Or set it dynamically based on vSphere version.
- Pro's: to set it statically, it's a trivial change and foolproof for any customer who's getting started on a recent NetApp HCI cluster
- Con's: if it's not set dynamically, folks who are still on vSphere v6.5 will get stuck. But assuming nobody RTFM I'd prefer that ez-rancher accommodates users who run v6.7 and newer. 

We just need one line in `terraform/modules/infrastructure/vsphere/11-inf.tf`:

```raw
resource "vsphere_virtual_machine" "node" {
  count            = var.node_count
  name             = format("${var.vm_name}-${var.type}%02d", count.index + 1)
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder           = var.vsphere_vm_folder
  num_cpus         = var.vm_cpu
  memory           = var.vm_ram
  guest_id         = data.vsphere_virtual_machine.template.guest_id
  hardware_version = "14" # hardcoded to HW v14 (vSphere 6.7+)
  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = length(data.vsphere_virtual_machine.template.network_interface_types) == 0 ? "vmxnet3" : data.vsphere_virtual_machine.template.network_interface_types[0]
  }
```

With this I was able to deploy successfully using PR #100:

![image](https://user-images.githubusercontent.com/16622642/100727673-88d1e200-3401-11eb-86d7-2f740d2ab635.png)

**Comment by bgentry-ntap** [comment]
Good find, might be a bit risky since it can't be downgraded: https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#hardware_version

But it would be easy to add an optional field for that on the ez-rancher side. We have avoided any kind of image modification or lifecycle management so far from the ez-rancher perspective.

**Comment by scaleoutsean** [comment]
Thank you. I stated some of my preferences, but I understand there are other concerns.

I can't find the exact doco link right now but I think new clusters we deploy are 6.7U1 while 6.5U2+ clusters can only be joined to. ESXi 6.5 has 11.5 months [to go](https://lifecycle.vmware.com/#/) until End of Support.
