### ISSUE TITLE
External snapshotter

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/ez-rancher#111]
Should ez-rancher deploy [external snapshotter](https://github.com/kubernetes-csi/external-snapshotter#csi-snapshotter) CRDs, validating Webhook, etc? 

That seems fairly complex for a manual deployment (especially the still optional Webhook), and if it's up to users most will choose to skip that step, which is what the readme file repeatedly warns about ("cluster admins choosing not to install the webhook server and participate in the phased release process can cause future problems when upgrading from v1beta1 to v1 volumesnapshot API") and `v1` volumesnapshot API just came out (in K8s v1.20).

Simialarly, after Trident Helm chart is deployed, VolumeSnapshotClass can't be created until external snapshotter is in place, so anyone wanting to take CSI snapshots will have no choice but to manually install external snapshottter - the CRDs need to be edited, etc. - it's not foolproof (example: I just spent hours trying to get external snapshotter to work on ez-rancher with v1.19 - `kubectl` reported snapshot create success,  but SF didn't show any snapshots or even API snapshot calls in Event log... I used to use Trident CSI snapshots before (OCP 3.11) without problems, so it's not like I never managed to have it work.)

**Comment by scaleoutsean** [comment]
I got snaps to work on ez-rancher with the "old" external snapshotter v2.1 (which is what's currently in the Trident docs; that version was deprecated in v1.16 and will be supported until v1.22). I also managed to get Kasten to work with Trident to take SolidFire snapshots and restore app data from them.
Earlier I tried the then-latest v3 which I couldn't get to work, maybe I didn't correctly configure it. v4 came out after that (several days ago).

**Comment by bgentry-ntap** [comment]
I don't think this belongs in ezr since this would target user clusters after the original deployment, not the rancher cluster that ezr is creating. I think this could make sense as an additional feature for the [trident installer](https://github.com/NetApp/ez-rancher-trident-installer) to also include the external-snapshotter crd. Probably not something for this repo

**Comment by scaleoutsean** [comment]
I agree with that. I did create enhancement request for this in the Trident repo thinking if they test and update the instructions we could add it in here. But perhaps users can directly use the official Trident documentation as you say.
