### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by jacobweinstock** [NetApp/ez-rancher#23]
this is a place holder for the first release.

there's plenty of functionality in here to make a release. we should define the release and its functionality. create some docs on what to expect and what we know as issues and how its being tested. i think the testing part is either just waiting for documentation or some polish on the functional tests that rancher server can deploy user clusters.

**Comment by bgentry-ntap** [comment]
https://github.com/NetApp/ez-rancher/releases/tag/v0.1.0
