### ISSUE TITLE
Our method of specifying ssh keys won't work with dockerized deploys

### ISSUE THREAD

**Issue by j-griffith** [NetApp/ez-rancher#35]
For ssh keys we use a variable where we just point to the .ssh key files we'd like to load.  This is handy and more convenient than say copy/pasting the actual keys; BUT it doesn't work in a dockerized context unless we load the ssh keys.

We could either add a docker volume that mounts our keys in the container or go back to pasting the keys in.

**Comment by j-griffith** [comment]
What might be a good option (discussed this with @bgentry-ntap via Slack):
Rather than specifying private/pub keys which are used for RKE set up and node->node connectivity; we could just drop those variables altogether and ALWAYS generate new pub/private keys for RKE to use.

Instead, we would then just create a new variable 'authorized_key' that would allow a user to specify an ssh pub-key to access the node.  This is appealing because it eliminates the security concerns around pasting or passing around private keys.

**Comment by bgentry-ntap** [comment]
@j-griffith et all, do we want to require the 'authroized_key' or keep it optional -- meaning no node access?

**Comment by j-griffith** [comment]
> @j-griffith et all, do we want to require the 'authorized_key' or keep it optional -- meaning no node access?

Personally I think we could keep it optional.  If an admin needs to access the VM they still have the keys we generate in the deliverables bundle.  The additional "authorized_key" variable would just be "convenient".  There are plenty of alternatives to getting authorized_keys added though (modify the cloud-init yourself, use a template image with your keys on it already etc).

**Comment by bgentry-ntap** [comment]
| they still have the keys we generate in the deliverables bundle

Ah, I thought we were removing the private keys. If that is the case, then I don't think we have eliminated any security concern with the private keys in the deliverables still
