### ISSUE TITLE
Shouldn't have a common ssh-key baked in the docker image

### ISSUE THREAD

**Issue by j-griffith** [NetApp/ez-rancher#36]
We currently generate ssh-keys as part of the docker build (https://github.com/NetApp/ez-rancher/blob/main/Dockerfile#L19) but that's not so good.  That means anybody could easily gain access by just downloading the same release/build of the container image and now they have ability to access someone elses terraform-rancher container.

**Comment by bgentry-ntap** [comment]
#37 closes this
