### ISSUE TITLE
proposal - specify versions

### ISSUE THREAD

**Issue by jacobweinstock** [NetApp/ez-rancher#76]
It has been requested by a small few but i think its worth discussing. Enable the ability to specify versions of things like (or possibly just adding a deliverable with the versions that were installed) 
* docker
* rancher/kubernetes
* cni, ingress, etc
* rke
* OS
* etc

what are the thoughts here? @bgentry-ntap @sgryczan @hulquest

**Comment by bgentry-ntap** [comment]
You can get all that from rancher or the deliverables already sans the OS image that is specified in the request. IDK, I'm fine adding it but seems like a low priority.

**Comment by scaleoutsean** [comment]
From RKE's building-the-provider document:

> If you use RKE v0.2.x or v0.1.x, please set proper branch.

It's not clear from README.md alone which version of the RKE TF provider should be used. In the past I've encountered bugs specific to minor releases of Ubuntu 18.04 OS (currently an "alias" URL) and Docker (I know RKE can ignore Docker version and go ahead with whatever is installed, but not sure if we support that approach or not), so the request seems sensible.

**Comment by bgentry-ntap** [comment]
The provider versions will be locked on the next release

**Comment by bgentry-ntap** [comment]
Release branch used to lock docker, rancher/k8s, and rke: https://github.com/NetApp/ez-rancher/tree/release/bryce-canyon

Main branch is locked via tf 0.14 dependency lock file. Periodic, manual updates to the tf dependencies will be done on main
